# Generated by Django 6.0.7 on 2026-07-21 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_last_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'User Logged In'), ('LOGOUT', 'User Logged Out'), ('CREATE_ACCOUNT', 'Account Created'), ('DELETE_ACCOUNT', 'Account Deleted'), ('TOGGLE_ACCOUNT', 'Account Status Changed'), ('CREATE_USER', 'Team Member Added'), ('DELETE_USER', 'Team Member Removed'), ('TOGGLE_USER', 'Team Member Status Changed')], max_length=50)),
                ('target', models.CharField(help_text="The company or user affected (e.g., 'IMPI Engineering')", max_length=255)),
                ('details', models.TextField(blank=True, help_text="Extra context (e.g., 'Changed status to Inactive')", null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
