# Generated by Django 6.0.7 on 2026-07-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'User Logged In'), ('LOGOUT', 'User Logged Out'), ('CREATE_ACCOUNT', 'Account Created'), ('DELETE_ACCOUNT', 'Account Deleted'), ('TOGGLE_ACCOUNT', 'Account Status Changed'), ('UPDATE_PLAN', 'Account Plan Updated'), ('CREATE_USER', 'Team Member Added'), ('DELETE_USER', 'Team Member Removed'), ('TOGGLE_USER', 'Team Member Status Changed')], max_length=50),
        ),
    ]
