# Generated by Django 6.0.7 on 2026-08-11 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_systemmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_trial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='trial_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='subscription_plan',
            field=models.CharField(choices=[('basic', 'Basic'), ('professional', 'Professional'), ('enterprise', 'Enterprise'), ('trail', 'Trail')], default='basic', max_length=20),
        ),
    ]
