# Generated by Django 6.0.7 on 2026-08-11 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_organization_is_trial_organization_trial_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='subscription_plan',
            field=models.CharField(choices=[('basic', 'Basic'), ('professional', 'Professional'), ('enterprise', 'Enterprise'), ('trial', 'Trial')], default='basic', max_length=20),
        ),
    ]
