# Generated by Django 6.0.7 on 2026-09-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_issuereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='has_ppm_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='quota_override',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
