# Generated by Django 6.0.7 on 2026-08-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_service', '0002_analysisreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisreport',
            name='processing_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
