# Generated by Django 6.0.7 on 2026-08-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_service', '0003_analysisreport_processing_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisreport',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='processeddocument',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
