# Generated by Django 6.0.7 on 2026-09-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_service', '0004_analysisreport_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processeddocument',
            name='document_type',
            field=models.CharField(choices=[('OM', 'Offering Memorandum'), ('T12', 'T12 Statement'), ('RENT_ROLL', 'Rent Roll'), ('PPM', 'Private Placement Memorandum')], max_length=20),
        ),
        migrations.AddField(
            model_name='analysisreport',
            name='document_type',
            field=models.CharField(choices=[('CRE', 'CRE Underwriting (OM/T12/Rent Roll)'), ('PPM', 'Private Placement Memorandum')], default='CRE', max_length=10),
        ),
    ]
